[profile.default]
src = 'src'
out = 'out'
libs = ["node_modules", "lib"]
remappings = [
    "ds-test/=lib/forge-std/lib/ds-test/src/",
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin/=lib/openzeppelin-contracts/"
]

verbosity = 4

# See more config options https://github.com/foundry-rs/foundry/tree/master/config